episodes_dict = {'sezon-1': ['7-zavarushka-na-pirushke', '10-chto-to-neladnoe-v-korolevstve', '11-lyubovnye-zalozhniki',
                             '13-derevyashka', '14-spravochnik', '15-tryasunchik', '16-serdechnyy-paren-rikardio',
                             '17-vremya-biznesa', '18-dva-moih-lyubimyh-cheloveka', '19-vospominaniya-gory-bum-bum',
                             '21-volshebnik', '22-vyselennye', '23-gorod-vorov', '24-vedmin-sad', '25-chto-takoe-zhizn',
                             '26-okean-straha', '27-kogda-tayut-svadebnye-kolokola', '28-podzemele', '30-gercog',
                             '31-gorod-urodov', '34-donni', '36-oruzhenosec', '38-son-v-dozhdlivyy-den',
                             '40-chto-vy-nadelali', '43-ego-geroy', '45-vor-potroshitel'],
                 'sezon-2': ['20-prishelec-iz-temnosfery', '29-glaza', '32-vernost-korolyu', '33-goryachaya-krov',
                             '35-rasskazhi-mne-skazochku', '37-lyubov-sliznyakov', '39-energichnoe-zhivotnoe',
                             '41-sila-kristallov', '42-drugie-pirogi', '44-sostrich-zhenskiy-lokon',
                             '46-komnata-ledyanyh-klinkov', '47-ee-roditeli', '48-boby', '50-tihiy-korol',
                             '51-nastoyaschiy-ty', '52-hraniteli-solnechnogo-sveta', '53-smert-v-rascvete',
                             '54-silnaya-syuzen', '55-tainstvennyy-poezd', '56-idi-so-mnoy', '57-bryuho-zverya',
                             '58-predel', '60-tvorcy-video', '61-teplovaya-podpis', '62-rokovaya-oploshnost',
                             '63-smertelnyy-uzhas'],
                 'sezon-3': ['65-prelestnye-zavoevateli', '66-iduschie-na-smert-privetstvuyut-tebya',
                             '67-vospominanie-o-vospominanii', '68-killer', '69-slishkom-molodaya', '70-chudovische',
                             '71-nepodvizhnye', '72-bitva-volshebnikov', '73-fionna-i-pirozhok', '74-chego-ne-hvatalo',
                             '75-yablochnyy-vor', '76-murashki', '77-vse-huzhe-i-huzhe', '79-krasotopiya',
                             '80-nikto-tebya-ne-uslyshit', '81-dzheyk-protiv-mi-myau', '82-spasibo', '83-novye-rubezhi',
                             '84-veselye-sekrety', '85-shkaf-marselin', '86-bumazhnyy-pit', '87-drugoy-put',
                             '88-princessa-prizrak', '89-papino-podzemele', '90-adskoe-plamya'],
                 'sezon-4': ['91-goryachaya-na-oschup', '92-pyat-priklyucharikov', '93-chudaki-v-pautine',
                             '94-mechty-o-lyubvi', '95-vozvraschenie-v-temnosferu-chast-1',
                             '96-malenkiy-papin-monstr-chast-2', '99-po-tvoim-sledam', '101-volk-obnimashka',
                             '102-moya-zhena-princessa-chudovische', '105-goliad', '106-za-granyu-zemnoy-realnosti',
                             '107-popalsya', '120-princessa-pechenka', '109-kartochnye-voyny', '110-syny-marsa',
                             '111-tiho-sgoraya', '112-detektiv-bimo', '113-korol-cherv', '114-ledi-i-pyzhka',
                             '115-ty-sozdala-menya', '116-kto-pobedit', '117-moment-zazhiganiya', '118-nehitroe-delce',
                             '119-pravlenie-gantera', '104-ya-pomnyu-tebya', '103-lich'],
                 'sezon-5': ['97-finn-parnishka', '98-pes-dzheyk', '100-esche-pyat-priklyucharikov', '121-na-dereve',
                             '122-malenkiy-narodec', '123-papa-dzheyk', '124-deyvi', '125-tainstvennyy-zastenok',
                             '126-eto-tvoya-vina', '127-chuvachok', '128-plohoy-malchugan', '129-sklep-s-kostyami',
                             '130-velikiy-pticechel', '131-saymon-i-marsi', '132-glyuk-est-glyuk',
                             '133-podushkolyandiya', '134-bimo-poteryalsya', '135-piknik-u-bublgum',
                             '136-kon-dzheyms-bakster', '137-shshsh', '138-kavaler',
                             '139-vecherinka-okonchena-senorita-ostrov', '140-poslednee-zadanie',
                             '141-esche-pyat-korotkih-shkazok', '142-konfetnye-ulicy', '143-tolko-volshebniki-durache',
                             '144-kostyum-iz-dzheyka', '145-byt-chem-to-bolshim', '146-nebesnaya-vedma',
                             '147-moroz-i-plamya', '148-slishkom-stara', '149-zemlya-i-voda', '150-sendvich-vremeni',
                             '151-hranilische-pamyati', '152-lyubovnye-igry', '153-poezd-podzemeliy',
                             '154-korobochnyy-princ', '155-zhazhda-krasnogo', '156-my-pochinili-gruzovik',
                             '157-chas-poteh-chast-1', '158-yama-chast-2', '159-dzheyms', '160-rutbir',
                             '162-yablochnaya-svadba', '163-travyanoy-mech', '164-pogremushkin', '165-krasnyy-tron',
                             '166-betti', '168-limonadik-chast-1', '167-proschet-vo-vremeni',
                             '170-predsmertnyy-spisok-del-billi'],
                 'sezon-6': ['171-probuzhdenie', '172-pobeg-iz-citadeli', '173-dzheyms-ii', '174-bashnya',
                             '175-grustnyy-kloun', '176-brizi', '177-pischevaya-cep', '178-mebel-i-myaso',
                             '179-princ-kotoryy-hotel-vsego', '180-nechto-bolshoe', '181-mladshiy-brat', '182-okarina',
                             '183-spasibo-za-yablochki-dzhuzeppe', '184-den-princess', '185-vozmezdie',
                             '186-byuro-rassledovaniy-dzhoshua-i-margaret', '188-prizrachnaya-muha',
                             '190-everythings-jake', '722-is-that-you', '723-jake-the-brick', '724-dentist',
                             '725-the-cooler', '726-the-pajama-war', '161-vechnozelenyy', '712-astralnyy-plan',
                             '732-gold-stars', '733-the-visitor', '189-gora', '736-dark-purple', '737-the-diary',
                             '741-walnuts-and-rain', '743-friends-forever', '721-jermaine', '749-chips-ice-cream',
                             '750-graybles-1000', '745-hoots', '757-water-park-prank', '748-you-forgot-your-floaties',
                             '747-be-sweet', '746-orgalorg', '744-on-the-lam', '752-hot-diggity-doom', '751-the-comet'],
                 'sezon-7': ['777-bonnie-neddy', '779-varmints', '780-cherry-cream-soda', '782-mama-said',
                             '783-football', '784-stakes-part-1-marceline-the-vampire-queen',
                             '785-stakes-part-2-everything-stays', '786-stakes-part-3-vamps-about',
                             '787-stakes-part-4-empress-eyes', '788-stakes-part-5-may-i-come-in',
                             '789-stakes-part-6-take-her-back', '790-stakes-part-7-checkmate',
                             '791-stakes-part-8-the-dark-cloud', '792-the-more-you-moe-the-moe-you-know',
                             '793-summer-showers', '794-angel-face', '795-president-porpoise-is-missing',
                             '796-blank-eyed-girl', '797-bad-jubies', '798-kings-ransom', '799-scamps', '800-crossover',
                             '801-i-am-a-sword', '805-flute-spell', '806-the-thin-yellow-line', '807-broke-his-crown',
                             '808-dont-look', '810-beyond-the-grotto', '811-lady-rainicorn-in-the-crystal-dimension',
                             '812-i-am-a-sword', '819-bun-bun', '820-normal-man', '822-elemental',
                             '823-five-short-tables', '816-the-music-hole', '824-daddy-daughter-card-wars',
                             '825-preboot', '827-reboot'],
                 'sezon-8': ['828-two-swords', '829-do-no-harm', '830-wheels', '831-high-strangeness',
                             '832-horse-and-ball', '833-jelly-beans-have-power', '834-islands-part-1-the-invitation',
                             '835-islands-part-2-whipple-the-happy-dragon', '836-part-3-mysterious-island',
                             '837-islands-part-4-imaginary-resources', '838-islands-part-5-hide-and-seek',
                             '839-islands-part-6-min-marty', '840-islands-part-7-helpers',
                             '841-islands-part-8-the-light-cloud'],
                 'sezon-9': ['842-orb', '843-skyhooks-elements-part-1', '844-bespoken-for-elements-part-2',
                             '845-winter-light-elements-part-3', '846-cloudy-elements-part-4',
                             '847-slime-central-elements-part-5', '848-happy-warrior-elements-part-6',
                             '849-hero-heart-elements-part-7', '850-skyhooks-ii-elements-part-8', '851-abstract',
                             '852-ketchup', '853-fionna-and-cake-and-fionna', '854-whispers', '855-three-buckets'],
                 'sezon-10': ['856-wild-hunt', '857-always-bmo-closed', '858-son-of-rap-bear', '859-bonniebel-bublegum',
                              '860-seventeen', '861-ring-of-fire', '862-marcy-hunson', '863-the-first-investigation',
                              '864-blenanas', '866-jake-the-starchild', '865-temple-of-mars', '867-gumbaldia',
                              '868-diamonds-lemons', '869-come-along-with-me'],
                 'mini-sezon': ['771-alls-well-that-rats-swell', '772-have-you-seen-the-muffin-mess',
                                '775-sow-do-you-like-them-apples', '781-podarki-zhneca'],
                 'frog-seasons': ['813-frog-seasons-01-spring', '814-frog-seasons-summer', '815-sezony-lyagushek-osen',
                                  '817-frog-seasons-winter', '826-frog-seasons-spring-again'],
                 'distant-lands': ['871-bimo', '873-obsidian', '875-snova-vmeste', '874-gorod-volshebnikov']}
